[project]
name = "pytest-kind-ng"
dynamic = ["version"]
description = "Kubernetes test support with KIND for pytest"
authors = [
    { name = "Henning Jacobs", email = "henning@jacobs1.de" },
    { name = "Jacob Tomlinson", email = "jacob@tomlinson.email" },
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Framework :: Pytest",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development :: Testing",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["platformdirs>=4.0"]

[project.urls]
Repository = "https://github.com/kr8s-org/pytest-kind-ng"

[project.entry-points.pytest11]
pytest-kind-ng = "pytest_kind.plugin"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "pytest_kind/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["pytest_kind"]

[tool.taskipy.tasks]
lint = "pre-commit run --all-files --hook-stage pre-commit && pre-commit run --all-files --hook-stage pre-push"
test = "coverage run --source=pytest_kind -m pytest tests/ && coverage report"
test-local = "python -m http.server --directory fake-download 8000 & KIND_DOWNLOAD_URL=http://localhost:8000/kind coverage run --source=pytest_kind -m pytest -v tests/ && coverage report"

[dependency-groups]
dev = [
    "pre-commit>=3.2.0",
    "kr8s>=0.19.1",
    "pytest-cov>=2.7",
    "pytest>=5.1",
    "taskipy>=1.14.1",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
