[project]
name = "aiohttp-helloworld"
version = "0.1.0"
description = "Basic example of pytest-kind-ng"
authors = [
    { name = "Henning Jacobs", email = "henning@jacobs1.de" },
]
requires-python = ">=3.7"
dependencies = []

[tool.taskipy.tasks]
docker = "docker build -t hjacobs/aiohttp-helloworld:latest ."
test = "task docker && pytest --cluster-name=aiohttp-helloworld"

[tool.uv]
package = false

[tool.uv.sources]
pytest-kind-ng = { path = "../..", editable = true }

[dependency-groups]
dev = [
    "pytest-kind-ng==22.11.1",
    "pytest>=5.1,<6",
    "taskipy>=1.14.1",
]
